# Generated by Django 4.1.2 on 2022-10-24 21:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=None)),
                ('preparation', models.TextField()),
                ('category', models.CharField(choices=[('F', 'Первые блюда'), ('S', 'Вторые блюда'), ('A', 'Закуски'), ('L', 'Салаты'), ('C', 'Кремы')], max_length=1)),
                ('preview', models.ImageField(blank=True, upload_to='preview/')),
            ],
        ),
    ]
